# Generated by Django 2.1.4 on 2018-12-27 10:14

from django.db import migrations, models
import tangtoc.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('content', models.TextField(verbose_name='Câu hỏi')),
                ('question_number', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Số thứ tự câu hỏi')),
                ('file', models.FileField(blank=True, upload_to=tangtoc.models.question_directory_path, verbose_name='File đính kèm')),
                ('solution', models.CharField(max_length=255, verbose_name='Đáp án')),
            ],
        ),
    ]
