# Generated by Django 2.1.4 on 2018-12-27 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tangtoc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='Đáp án')),
                ('time_posted', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian trả lời')),
                ('question_number', models.IntegerField(verbose_name='Câu hỏi số')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='question_number',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Câu hỏi số'),
        ),
    ]
