# Generated by Django 2.1.4 on 2018-12-29 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tangtoc', '0003_auto_20181229_2140'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('question_number', 'round')},
        ),
    ]
