# Generated by Django 2.1.4 on 2019-01-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangtoc', '0006_auto_20190106_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='contestant',
            field=models.CharField(blank=True, choices=[('ts1', 'Thí sinh 1'), ('ts2', 'Thí sinh 2'), ('ts3', 'Thí sinh 3'), ('ts4', 'Thí sinh 4')], max_length=255, verbose_name='Thí sinh'),
        ),
    ]
