# Generated by Django 2.1.4 on 2019-01-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangtoc', '0008_question_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type_knowledge',
            field=models.CharField(blank=True, choices=[('toan', 'toan'), ('ly', 'ly'), ('hoa', 'hoa'), ('anh', 'anh'), ('van', 'van'), ('su', 'su'), ('sinh', 'sinh'), ('dia', 'dia'), ('tin', 'tin'), ('cau_hoi_chung', 'cau_hoi_chung')], max_length=255, null=True, verbose_name='Lĩnh vực'),
        ),
    ]
