# Generated by Django 2.1.4 on 2019-01-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangtoc', '0009_question_type_knowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='used',
            field=models.BooleanField(default=False, verbose_name='Đã sử dụng'),
        ),
    ]
