# Generated by Django 2.1.5 on 2019-01-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Tên hiển thị'),
        ),
    ]
