# Generated by Django 2.1.3 on 2019-01-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_myuser_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='grade',
            field=models.IntegerField(blank=True, default=0, verbose_name='Điểm'),
        ),
    ]
