# Generated by Django 2.1.3 on 2018-11-23 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_auto_20181123_0613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='profle_pic',
            new_name='profile_pic',
        ),
    ]
