# Generated by Django 2.1.3 on 2018-11-24 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_auto_20181124_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='users',
            new_name='members',
        ),
    ]
