# Generated by Django 2.1.3 on 2018-11-24 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='project',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
