# Generated by Django 2.1.3 on 2018-12-08 04:55

from django.db import migrations, models
import userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0014_auto_20181207_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='userprofile/default_profile.jpg', null=True, upload_to=userprofile.models.user_directory_path),
        ),
    ]
