# Generated by Django 2.1.4 on 2018-12-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0016_auto_20181227_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='email',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
