# Generated by Django 2.1.4 on 2018-12-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0017_myuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_contestant',
            field=models.BooleanField(default=True),
        ),
    ]
